### ISSUE TITLE
SpoornPacks (fabric) cause a loading loop if Artifacts-Fabric is also installed

### ISSUE THREAD

**Issue by KMFrench1** [spoorn/SpoornPacks#1]
I trying to add myloot to my game, when I did the game fails to load. The red mojang screen starts, the bar load till the end then restarts. this just keeps happening forever till I kill the process.
I thought it was myloot that might be the problem so I removed it but left in SpoornsPacks (https://github.com/spoorn/SpoornPacks) but this issue continued to happen.
I have tried different versions 
3.2
3.1
3.0

When I installed version 2.1 of SpoornPack the game finally loaded properly.
unfortunately myloot does not work with that version.

Here is the log for the attempt with version 3.2, without myloot installed.
https://paste.ee/p/4vL8p
The loop start at line 2276.
looks like something about a mimic texture causes all the resource pack to unload and try to load again.
The mimic if from the Artifacts mod, the 1.18 release is on github (https://github.com/florensie/artifacts-fabric/releases/tag/v6.0.0)

If I remove artifact, then SpoornPack and myloot both load.
Not sure which mod is causing the problem spoornpack or artifacts, so i am reporting it to both.

Thanks for any response :)

**Comment by spoorn** [comment]
Not exactly sure what Artifacts is doing, but seems it's rendering Mimic chests in custom way which ends up causing the BlockEntity to be null for some reason.  Anyways, I worked around it in the 3.3 release: https://www.curseforge.com/minecraft/mc-mods/spoornpacks/files/3659739

Let me know if the issue is still there after using 3.3
